# Generated by Django 5.0.6 on 2024-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(default='https://www.ejemplo.com'),
        ),
    ]
